use alloy::sol;

// Export the ABI for the IEigenDACertVerifier contract.
// This abi is generated by the build.rs script.
// See the comments in build.rs for more details.
sol! {
    IEigenDACertVerifier, concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated/abis/IEigenDACertVerifier.json"),
}
